sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "iojs"
before_script:
  - npm install -g grunt-cli
script: grunt
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules