# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - cmd: npm test
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json